basePath: /api
definitions:
  model.Service:
    type: object
host: localhost:8080
info:
  contact: {}
  description: Mid-Level Backend Assessment Microservice for BRB.
  title: BRB Microservice API
  version: "1.0"
paths:
  /api/services/:
    post:
      consumes:
      - application/json
      description: Admin-only endpoint to create a new service
      parameters:
      - description: Service payload
        in: body
        name: service
        required: true
        schema:
          $ref: '#/definitions/model.Service'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
      summary: Create a service
      tags:
      - services
swagger: "2.0"
